using System.Text.Json.Serialization;

namespace PayPalServerSdk.Models;

/// <summary>
/// This object defines a customer in your system. Use it to manage customer profiles, save payment methods and contact details.
/// </summary>
public record Customer
{
    /// <summary>
    /// The unique ID for a customer generated by PayPal.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// Merchants and partners may already have a data-store where their customer information is persisted. Use merchant_customer_id to associate the PayPal-generated customer.id to your representation of a customer.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("merchant_customer_id")]
    public string? MerchantCustomerId { get; init; }
}
